name: Professor Fox
favicon: null
layout_spectrum: 0.8774709349963814
typography_spectrum: 0.04195218998938799
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7314383464399725
  lightness: 0.43307252088561654
  saturation: 0.5036958020646125
  rhythmicContrast: 0.09611718123778701
purpose: []
